-- =====================================================================
-- Controle de Documentação da Frota — IPVA, Licenciamento, Seguro e
-- Manutenções Preventivas.
--
-- Execute este script uma única vez no SQL Editor do Supabase do projeto.
-- O trigger `rls_auto_enable` já habilita RLS e cria a policy padrão
-- (`rls_auto_default`, FOR ALL TO authenticated USING(true) WITH CHECK(true))
-- em toda tabela nova, mas os comandos abaixo são explícitos e idempotentes
-- para o caso de o trigger falhar ou ser removido no futuro.
-- =====================================================================

-- ── Veículos ──────────────────────────────────────────────────────────
create table if not exists public.frota_veiculos (
    id           bigint generated by default as identity primary key,
    placa        text not null unique,
    marca        text not null,
    modelo       text not null,
    ano_modelo   text,
    cor          text,
    uf           text not null default 'GO',
    renavam      text,
    motorista    text,
    km_atual     numeric,
    ativo        boolean not null default true,
    observacao   text,
    -- Caminho do objeto no bucket `frota-documentos-pdfs` (CRLV ou outro
    -- documento do próprio veículo, anexado direto no cadastro). Nulo = sem anexo.
    documento_pdf_path text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

alter table public.frota_veiculos add column if not exists documento_pdf_path text;

-- ── Calendário de vencimento (IPVA / Licenciamento) por final de placa ──
-- Uma linha por (ano, tipo, final_placa). `tipo` = 'IPVA' ou 'LICENCIAMENTO'.
create table if not exists public.frota_calendario (
    id           bigint generated by default as identity primary key,
    ano          int not null,
    tipo         text not null check (tipo in ('IPVA', 'LICENCIAMENTO')),
    final_placa  text not null check (final_placa in ('0','1','2','3','4','5','6','7','8','9')),
    vencimento   date not null,
    created_at   timestamptz not null default now(),
    unique (ano, tipo, final_placa)
);

-- ── Documentos (IPVA / Licenciamento / Seguro) por veículo e ano ───────
create table if not exists public.frota_documentos (
    id                bigint generated by default as identity primary key,
    veiculo_id        bigint not null references public.frota_veiculos(id) on delete cascade,
    tipo              text not null check (tipo in ('IPVA', 'LICENCIAMENTO', 'SEGURO')),
    ano               int not null,
    valor             numeric,
    pago              boolean not null default false,
    data_pagamento    date,
    -- Vencimento manual: obrigatório para SEGURO; para IPVA/LICENCIAMENTO só é
    -- necessário se o veículo não for de Goiás (aí o cálculo automático pelo
    -- calendário não se aplica).
    vencimento_manual date,
    seguradora        text,
    apolice           text,
    vigencia_inicio   date,
    vigencia_fim      date,
    observacao        text,
    -- Caminho do objeto no bucket de storage `frota-documentos-pdfs`
    -- (guia do IPVA, CRLV, apólice digitalizada etc.). Nulo = sem anexo.
    pdf_path          text,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    unique (veiculo_id, tipo, ano)
);

alter table public.frota_documentos add column if not exists pdf_path text;

-- ── Manutenções preventivas por veículo ─────────────────────────────────
create table if not exists public.frota_manutencoes (
    id              bigint generated by default as identity primary key,
    veiculo_id      bigint not null references public.frota_veiculos(id) on delete cascade,
    tipo            text not null,
    data_realizada  date not null,
    km_realizada    numeric,
    proxima_data    date,
    proximo_km      numeric,
    observacao      text,
    created_at      timestamptz not null default now()
);

-- ── Histórico de pagamentos (ledger livre, com comprovante em PDF) ─────
-- Diferente de frota_documentos (1 linha por veículo/tipo/ano, para o status
-- vigente), esta é uma lista de lançamentos: permite registrar parcelas de
-- IPVA, reembolsos de manutenção, renovações de seguro etc., cada um com seu
-- próprio comprovante digitalizado.
create table if not exists public.frota_pagamentos (
    id             bigint generated by default as identity primary key,
    veiculo_id     bigint not null references public.frota_veiculos(id) on delete cascade,
    tipo           text not null check (tipo in ('IPVA', 'LICENCIAMENTO', 'SEGURO', 'MANUTENCAO', 'OUTRO')),
    descricao      text,
    valor          numeric,
    data_pagamento date not null,
    pdf_path       text,
    observacao     text,
    created_at     timestamptz not null default now()
);

-- ── Parâmetros gerais (ano vigente, janela de alerta, taxas) ───────────
create table if not exists public.frota_parametros (
    chave  text primary key,
    valor  text not null
);

insert into public.frota_parametros (chave, valor) values
    ('ano_vigente', '2026'),
    ('dias_alerta', '30'),
    ('taxa_licenciamento', '274.61'),
    ('taxa_licenciamento_atraso', '347.12')
on conflict (chave) do nothing;

-- ── Calendário Detran-GO / SEFAZ-GO 2026 ────────────────────────────────
-- IPVA/Licenciamento 2026: finais 1 e 2 vencem 15/09; finais 3 a 0 vencem 15/10.
insert into public.frota_calendario (ano, tipo, final_placa, vencimento)
select 2026, tipo, final_placa, vencimento
from (values
    ('IPVA', '1', date '2026-09-15'), ('IPVA', '2', date '2026-09-15'),
    ('IPVA', '3', date '2026-10-15'), ('IPVA', '4', date '2026-10-15'),
    ('IPVA', '5', date '2026-10-15'), ('IPVA', '6', date '2026-10-15'),
    ('IPVA', '7', date '2026-10-15'), ('IPVA', '8', date '2026-10-15'),
    ('IPVA', '9', date '2026-10-15'), ('IPVA', '0', date '2026-10-15'),
    ('LICENCIAMENTO', '1', date '2026-09-15'), ('LICENCIAMENTO', '2', date '2026-09-15'),
    ('LICENCIAMENTO', '3', date '2026-10-15'), ('LICENCIAMENTO', '4', date '2026-10-15'),
    ('LICENCIAMENTO', '5', date '2026-10-15'), ('LICENCIAMENTO', '6', date '2026-10-15'),
    ('LICENCIAMENTO', '7', date '2026-10-15'), ('LICENCIAMENTO', '8', date '2026-10-15'),
    ('LICENCIAMENTO', '9', date '2026-10-15'), ('LICENCIAMENTO', '0', date '2026-10-15')
) as t(tipo, final_placa, vencimento)
on conflict (ano, tipo, final_placa) do nothing;

-- ── Bucket de storage para os PDFs (guias, CRLV, apólices, comprovantes) ─
-- Segue o mesmo padrão do bucket `project-3d-pdfs` (js/project_modal_shared.js):
-- privado, acesso só por signed URL, path = "<uuid>.pdf".
insert into storage.buckets (id, name, public)
values ('frota-documentos-pdfs', 'frota-documentos-pdfs', false)
on conflict (id) do nothing;

do $$
begin
    if not exists (select 1 from pg_policies where tablename = 'objects' and schemaname = 'storage' and policyname = 'frota_pdfs_authenticated') then
        create policy frota_pdfs_authenticated on storage.objects for all to authenticated
            using (bucket_id = 'frota-documentos-pdfs')
            with check (bucket_id = 'frota-documentos-pdfs');
    end if;
end $$;

-- ── RLS (idempotente — ver nota no topo do arquivo) ─────────────────────
alter table public.frota_veiculos    enable row level security;
alter table public.frota_calendario  enable row level security;
alter table public.frota_documentos  enable row level security;
alter table public.frota_manutencoes enable row level security;
alter table public.frota_pagamentos  enable row level security;
alter table public.frota_parametros  enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where tablename = 'frota_veiculos' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_veiculos for all to authenticated using (true) with check (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'frota_calendario' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_calendario for all to authenticated using (true) with check (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'frota_documentos' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_documentos for all to authenticated using (true) with check (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'frota_manutencoes' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_manutencoes for all to authenticated using (true) with check (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'frota_pagamentos' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_pagamentos for all to authenticated using (true) with check (true);
    end if;
    if not exists (select 1 from pg_policies where tablename = 'frota_parametros' and policyname = 'rls_auto_default') then
        create policy rls_auto_default on public.frota_parametros for all to authenticated using (true) with check (true);
    end if;
end $$;
